name: "issue maker"

description: "create and issue with a cat fact as the body"

iputs:
  isuueTitle:
    description: "A name for the cat-fact issue"
    required: true
    defalut: "A cat fact for you"
  
  catFact:
    description: "the cat fact retreived from a previous action"
    required: true
    default: "Mona is an Octocat"
    
  repoToken:
    description: "Authentication token, use secretes.GITHUB_TOKEN"
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
